### PR TITLE
Added ResponseErrorWriter interface to allow for custom error json ma…

### PR DESCRIPTION
**Pull request by Inflatablewoman**
…rshalling. Added tests to ensure backward compatibilty

Please review and merge.

### CODE REVIEW

**Comment by Inflatablewoman** [comment]
Refactored taking into account what you said.  The other errors, I am ok with being in the tigertonic format.

**Comment by Inflatablewoman** [comment]
Finally twigged what you meant.  The calls are no made in place.  All places that did similar error output have been centralised into using the ResponseErrorWriter functions.

**Comment by Inflatablewoman** [comment]
Where possible code also uses 

```go
ResponseErrorWriter.WritePlaintextError(w, notFoundErr)
````

where appropriate.

**Comment by willfaught** [comment]
LGTM

I'm not the repo owner, though; one of them will have to accept the PR. Is one of them watching? :)

**Comment by mihasya** [comment]
@willfaught @Inflatablewoman Hi hi, yes, been tracking since the original issue. Will take a look at it this week, unless @wadey gets to it first.

**Comment by Inflatablewoman** [comment]
The sooner the better would be great, I need to get this into a build by the end of the week.  Would prefer to not use my fork if I dont have to.  Any estimate?

**Comment by mihasya** [comment]
:+1:

**Pull request merged**
